SET PASSWORD FOR root@localhost = PASSWORD('123456');
GRANT CREATE,CREATE VIEW,DROP,ALTER,SELECT,INSERT,UPDATE,DELETE,INDEX,LOCK TABLES,SHOW VIEW,REFERENCES ON *.* TO zentao@localhost IDENTIFIED BY '123456';
